create table items (
  id 				 integer identity,
  quotation_id 		 integer,
  bathroom_id 		 integer,
  serial_no 		 integer,
  item_code_l 		 varchar(200),
  item_code_m 		 varchar(200),
  item_code_s 		 varchar(200),
  item_description_s longvarchar,
  item_description_l longvarchar,
  quantity 			 integer,
  mrp 				 decimal(10, 2),
  nrp 				 decimal(10, 2),
  discount 			 decimal(10, 2),
  vat_percentage 	 decimal(10, 2),
  nrp_without_vat 	 decimal(10, 2),
  rd_without_vat 	 decimal(10, 2),
  vat_amount 		 decimal(10, 2),
  rd_including_vat   decimal(10, 2),
  margin_amount 	 decimal(10, 2),
  margin_percentage  decimal(10, 2),
  image 			 integer,
  bathroom_element   integer,
  total_amount         decimal(10, 2)
)